### ISSUE TITLE
Take Picture with Preview

### ISSUE THREAD

**Issue by willyantows** [spikehip/dslrbrowser-ios#1]
Hi, is possible to control camera to take picture with preview in ios app?

**Comment by spikehip** [comment]
Hi
currently as the app name also suggests, camera control is not possible and will not be the priority goal of this app. 
However it is planned to implement the PTP/IP protocol which enables the control of the camera. 
Some work is already prepared, PTP/IP cameras are already discovered and shown with a separate icon on the camera list. 
(around https://github.com/spikehip/dslrbrowser-ios/blob/master/dslrbrowser/CameraTableViewController.swift#L238 )
